serverName: "lobby"

protect: # Tick
  coreBlock: "DIAMOND_BLOCK" #Not ID, But Material
  defaultStartTime: 1728000
  createPrice: 10

fuel:
  price: 10.0
  fuelRequirements:
    # Required secondsPerFuel: above 0.5 (because TunaLands only checks and consumes fuel every 0.5 seconds)
    # Recommended secondsPerFuel: above 1
    - numOfMembers: 1
      secondsPerFuel: 120.0

    - numOfMembers: 4
      secondsPerFuel: 60.0

    - numOfMembers: 100
      secondsPerFuel: 0.1

recommend: # Tick
  reset: 1728000
  cooldown: 1728000

command:
  cooldown: #Tick
    rejoin: 5184000 #3d
    visit: 100 #5s
    spawn: 100 #5s
  price:
    setSpawnPrice: 10
    renamePrice: 10

limitWorld:
  - world_nether
  - world_the_end

flag:
  price:
    takeProtectFlagPrice: 10
    releaseProtectFlagPrice: 5
    takeFarmFlagPrice: 10
    releaseFarmFlagPrice: 5
  farm:
    limitFarmOccupied: 10