serverName: "lobby"

#All time units are in 'tick' units.
maxMemberLimit: 10
maxAlbaLimit: 10

protect:
  #Material type https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  coreBlock: "DIAMOND_BLOCK"
  createPrice: 10
  limitOccupied:
    - numOfMembers: 1
      chunk: 10

    - numOfMembers: 3
      chunk: 30

    - numOfMembers: 5
      chunk: 50

    - numOfMembers: 7
      chunk: 70

farm:
  limitOccupied: 10

flag:
  price:
    takeProtectFlagPrice: 10
    releaseProtectFlagPrice: 5
    activePrice:
      - chunk: 0
        price: 0

      - chunk: 1
        price: 10

      - chunk: 5
        price: 15

      - chunk: 10
        price: 30

    takeFarmFlagPrice: 10
    releaseFarmFlagPrice: 5

fuel:
  defaultFuel: 3
  price: 10.0
  # Every fuel decrease when 6 A.M
  # Hours of day 0~23
  imposeTime: 6
  fuelRequirements:
    # Recommended dayPerFuel: above 0
    - numOfMembers: 1
      dayPerFuel: 1

    - numOfMembers: 2
      dayPerFuel: 2

    - numOfMembers: 5
      dayPerFuel: 3

    - numOfMembers: 7
      dayPerFuel: 4

recommend:
  reset: 1728000 #1d
  cooldown: 1728000 #1d

command:
  cooldown:
    rejoin: 5184000 #3d
    # Teleport effect cooldown
    visit: 100 #5s
    spawn: 100 #5s
  price:
    setSpawnPrice: 10
    renamePrice: 10

limitWorld:
  - world_nether
  - world_the_end

ignoreWorld:
  - spawn