serverName: "lobby"

protect: # Tick
  coreBlock: "DIAMOND_BLOCK" #Not ID, But Material
  createPrice: 10

fuel:
  defaultFuel: 3600
  price: 10.0
  fuelRequirements:
    # Recommended secondsPerFuel: above 0
    # Only double type can read
    - numOfMembers: 1
      secondsPerFuel: 0.5

    - numOfMembers: 2
      secondsPerFuel: 1.0

    - numOfMembers: 5
      secondsPerFuel: 6.0

    - numOfMembers: 7
      secondsPerFuel: 10.0

recommend: # Tick
  reset: 1728000
  cooldown: 1728000

command:
  cooldown: #Tick
    rejoin: 5184000 #3d
    visit: 100 #5s
    spawn: 100 #5s
  price:
    setSpawnPrice: 10
    renamePrice: 10

limitWorld:
  - world_nether
  - world_the_end

flag:
  price:
    takeProtectFlagPrice: 10
    releaseProtectFlagPrice: 5
    takeFarmFlagPrice: 10
    releaseFarmFlagPrice: 5
  farm:
    limitFarmOccupied: 10