serverName: "lobby"

database:
  name: 'test'
  ip: 'localhost'
  port: 3306
  username: 'root'
  password: 'test'
  encoding: 'utf-8'

protect: # Tick
  coreBlock: "DIAMOND_BLOCK" #Not ID, But Material
  defaultStartTime: 1728000
  createPrice: 10

fuel:
  m30: 30
  h1: 50
  h6: 290
  h12: 570
  h24: 1100

recommend: # Tick
  reset: 1728000
  cooldown: 1728000

command:
  cooldown: #Tick
    rejoin: 5184000 #3d
    visit: 100 #5s
    spawn: 100 #5s
  price:
    setSpawnPrice: 10
    renamePrice: 10

limitWorld:
  - world_nether
  - world_the_end