name: TunaLands
main: com.salkcoding.tunalands.TunaLands
version: 1.2.2-alpha
description: Protect lands with some money
api-version: 1.19
author: Salk_Coding
depend:
  - Metamorphosis
  - DecentHolograms
  - Don
  - Vault
  - BukkitLinked
  - ProtocolLib
commands:
  tunaland:
    description: Base command
    usage: /tunaland help, /tl help
    aliases: [tl]