name: TunaLands
main: com.salkcoding.tunalands.TunaLands
version: 1.2.9
description: Protect lands with some money
api-version: 1.20
author: Salk_Coding
depend:
  - Metamorphosis
  - Don
  - Vault
  - BukkitLinked
  - ProtocolLib
commands:
  tunaland:
    description: Base command
    usage: /tunaland help, /tl help
    aliases: [tl]