name: TunaLands
main: com.salkcoding.tunalands.TunaLands
version: 1.1.6-hofix-1-SNAPSHOT
description: Protect lands with some money
api-version: 1.18
author: Salk_Coding
depend:
  - Metamorphosis
  - HolographicDisplays
  - Don
  - Vault
  - BukkitLinked
commands:
  tunaland:
    description: Base command
    usage: /tunaland help, /tl help
    aliases: [tl]